/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryAdjustmentsRouteImport } from './routes/inventory.adjustments'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresStoreIdRouteImport } from './routes/stores.$storeId'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as InventoryCountsIndexRouteImport } from './routes/inventory.counts.index'
import { Route as InventoryCountsCountIdRouteImport } from './routes/inventory.counts.$countId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAdjustmentsRoute = InventoryAdjustmentsRouteImport.update({
  id: '/inventory/adjustments',
  path: '/inventory/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryCountsIndexRoute = InventoryCountsIndexRouteImport.update({
  id: '/inventory/counts/',
  path: '/inventory/counts/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryCountsCountIdRoute = InventoryCountsCountIdRouteImport.update({
  id: '/inventory/counts/$countId',
  path: '/inventory/counts/$countId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/restaurants': typeof RestaurantsRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/inventory/counts/$countId': typeof InventoryCountsCountIdRoute
  '/inventory/counts/': typeof InventoryCountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/restaurants': typeof RestaurantsRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/stores': typeof StoresIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/inventory/counts/$countId': typeof InventoryCountsCountIdRoute
  '/inventory/counts': typeof InventoryCountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/restaurants': typeof RestaurantsRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/inventory/counts/$countId': typeof InventoryCountsCountIdRoute
  '/inventory/counts/': typeof InventoryCountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/restaurants'
    | '/inventory/adjustments'
    | '/stores/$storeId'
    | '/inventory/'
    | '/stores/'
    | '/transfers/'
    | '/inventory/counts/$countId'
    | '/inventory/counts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business'
    | '/restaurants'
    | '/inventory/adjustments'
    | '/stores/$storeId'
    | '/inventory'
    | '/stores'
    | '/transfers'
    | '/inventory/counts/$countId'
    | '/inventory/counts'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/restaurants'
    | '/inventory/adjustments'
    | '/stores/$storeId'
    | '/inventory/'
    | '/stores/'
    | '/transfers/'
    | '/inventory/counts/$countId'
    | '/inventory/counts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  RestaurantsRoute: typeof RestaurantsRoute
  InventoryAdjustmentsRoute: typeof InventoryAdjustmentsRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
  InventoryCountsCountIdRoute: typeof InventoryCountsCountIdRoute
  InventoryCountsIndexRoute: typeof InventoryCountsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/adjustments': {
      id: '/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof InventoryAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/counts/': {
      id: '/inventory/counts/'
      path: '/inventory/counts'
      fullPath: '/inventory/counts/'
      preLoaderRoute: typeof InventoryCountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/counts/$countId': {
      id: '/inventory/counts/$countId'
      path: '/inventory/counts/$countId'
      fullPath: '/inventory/counts/$countId'
      preLoaderRoute: typeof InventoryCountsCountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  RestaurantsRoute: RestaurantsRoute,
  InventoryAdjustmentsRoute: InventoryAdjustmentsRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  TransfersIndexRoute: TransfersIndexRoute,
  InventoryCountsCountIdRoute: InventoryCountsCountIdRoute,
  InventoryCountsIndexRoute: InventoryCountsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
